name: Deploy github pages for repo

on:
  workflow_dispatch:

env:
  REF: ${{ github.ref }}
  AUTHOR: ${{ secrets.RELEASE_USERNAME }}
  PAT: ${{ secrets.RELEASE_TOKEN }}
  ORG: Ananda-Aropa
  BRANCH: devel
  WORKFLOW: build_deb.yml

jobs:
  build-and-deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build repository
        uses: Ananda-Aropa/build-deb-repo@devel
        with:
          label: Ananda-Aropa debian repo
          origin: blisslabs.org
          desc: Ananda-Aropa Debian repo
          gpg_signing_key: "${{ secrets.GPG_SIGNING_KEY }}"
          max_download_retries: 10
          download_retry_wait: 30
          downloader: curl
          from_metadatas: ""
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_username: ${{ github.actor }}
          from_github_actions: |
            ${{ env.ORG }}/grub-android-prober@${{ env.BRANCH }}:${{ env.WORKFLOW }}
            ${{ env.ORG }}/grub2-themes@${{ env.BRANCH }}:${{ env.WORKFLOW }}
            ${{ env.ORG }}/efifs-debian@${{ env.BRANCH }}:${{ env.WORKFLOW }}
            ${{ env.ORG }}/refind-files-i386@${{ env.BRANCH }}:${{ env.WORKFLOW }}
            ${{ env.ORG }}/aaropa_busybox@${{ env.BRANCH }}:${{ env.WORKFLOW }}
            ${{ env.ORG }}/aaropa_calamares@${{ env.BRANCH }}:${{ env.WORKFLOW }}
            ${{ env.ORG }}/aaropa_calamares_modules_bass@${{ env.BRANCH }}:${{ env.WORKFLOW }}
            ${{ env.ORG }}/calamares_branding_bassos@${{ env.BRANCH }}:${{ env.WORKFLOW }}
            ${{ env.ORG }}/calamares_branding_blissos@${{ env.BRANCH }}:${{ env.WORKFLOW }}
            ${{ env.ORG }}/calamares_branding_lineageos@${{ env.BRANCH }}:${{ env.WORKFLOW }}
            ${{ env.ORG }}/aaropa_keyring@${{ env.BRANCH }}:${{ env.WORKFLOW }}
            ${{ env.ORG }}/android-tools@${{ env.BRANCH }}:${{ env.WORKFLOW }}
            ${{ env.ORG }}/clang-android-debian@${{ env.BRANCH }}:${{ env.WORKFLOW }}
            ${{ env.ORG }}/linux-zenith@${{ env.BRANCH }}:${{ env.WORKFLOW }}
            ${{ env.ORG }}/initrd-aaropa-linux@${{ env.BRANCH }}:${{ env.WORKFLOW }}
      
      - name: Extract artifact
        run: unzip -o dist.zip

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Trigger Workflow after deployment
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: Ananda-Aropa
          repo: aaropa_rootfs_base
          github_token: ${{ env.PAT }}
          github_user: ${{ env.AUTHOR }}
          workflow_file_name: build_rootfs.yml
          ref: latest
          trigger_workflow: true
          wait_workflow: false
